#!/bin/bash
# resto test case pragmatic proof path
cwm resto.n3  --think --filter=restoG.n3 --why > resto-cwm-proof.n3
eye resto-cwm-proof.n3  --query step-count.n3 --nope 2>/dev/null | grep inferences
cwm resto2.n3 --think --filter=restoG.n3 --why > resto-cwm-proof2.n3
eye resto-cwm-proof2.n3 --query step-count.n3 --nope 2>/dev/null | grep inferences
